version: '3'

services:
  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    env_file:
      - .env
    volumes:
      - ./promtail-config.yaml:/etc/promtail/config.yml
      - /var/lib/docker/containers:/var/lib/docker/containers:ro   # Docker container logs
      - /var/run/docker.sock:/var/run/docker.sock:ro    # Docker socket for container discovery
    ports:
      - "9080:9080"
    command:
      - -config.file=/etc/promtail/config.yml
      - -config.expand-env=true
    restart: unless-stopped
    networks:
      - promtail-network

networks:
  promtail-network:
    driver: bridge
