server:
  http_listen_port: 9080

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://167.172.70.195:3100/loki/api/v1/push
    batchwait: 10s          # Wait up to 10s to batch logs
    batchsize: 102400       # Batch size in bytes (100KB)
    backoff_config:
      min_period: 1s
      max_period: 5m
      max_retries: 5
    timeout: 15s

scrape_configs:
  - job_name: system
    static_configs:
      - targets:
          - localhost
        labels:
          job: system
          host: ${HOSTNAME}
          __path__: /var/log/*.log
    pipeline_stages:
      - match:
          selector: '{job="system"}'
          stages:
            - drop:
                older_than: 12h

  - job_name: django
    static_configs:
      - targets:
          - localhost
        labels:
          job: django
          host: ${HOSTNAME}
          __path__: /django-logs/django_requests.log
    pipeline_stages:
      - match:
          selector: '{job="django"}'
          stages:
            - drop:
                older_than: 12h
