server:
  http_listen_port: 9080

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://LOKI_HOST:3100/loki/api/v1/push  # Replace LOKI_HOST with your Loki server address

scrape_configs:
  - job_name: system
    static_configs:
      - targets:
          - localhost
        labels:
          job: system
          host: ${HOSTNAME}
          __path__: /var/log/*.log

  - job_name: django
    static_configs:
      - targets:
          - localhost
        labels:
          job: django
          host: ${HOSTNAME}
          __path__: /django-logs/django_requests.log
