server:
  http_listen_port: 9080

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://167.172.70.195:3100/loki/api/v1/push
    batchwait: 10s          # Wait up to 10s to batch logs
    batchsize: 102400       # Batch size in bytes (100KB)
    backoff_config:
      min_period: 1s
      max_period: 5m
      max_retries: 5
    timeout: 15s

scrape_configs:
  - job_name: python_green
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
        filters:
          - name: name
            values: ["python_green"]
    relabel_configs:
      - source_labels: ['__meta_docker_container_name']
        regex: '/(.*)'
        target_label: 'container'
      - source_labels: ['__meta_docker_container_log_stream']
        target_label: 'stream'
    pipeline_stages:
      - json:
          expressions:
            timestamp: time
            stream: stream
            message: log
      - timestamp:
          source: timestamp
          format: RFC3339Nano
      - labels:
          stream:
      - output:
          source: message
      - match:
          selector: '{job="python_green"}'
          stages:
            - drop:
                older_than: 12h


