version: "3.8"

services:
  loki:
    image: grafana/loki:2.9.8   # change to 'latest' if you prefer
    command: -config.file=/etc/loki/config.yml
    ports:
      - "3100:3100"
    volumes:
      - ./loki-config.yml:/etc/loki/config.yml:ro
      - loki-data:/loki
    restart: unless-stopped

  # (Optional) Grafana, already wired to Loki
  grafana:
    image: grafana/grafana:10.4.8
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-data:/var/lib/grafana
      - ./provisioning/datasources:/etc/grafana/provisioning/datasources
    depends_on:
      - loki
    restart: unless-stopped

volumes:
  loki-data:
  grafana-data: