server:
  http_listen_port: 3100
  grpc_listen_port: 9095

auth_enabled: false

common:
  instance_addr: 127.0.0.1
  path_prefix: /loki
  storage:
    filesystem:
      chunks_directory: /loki/chunks
      rules_directory: /loki/rules
  ring:
    kvstore:
      store: inmemory
  replication_factor: 1

ingester:
  wal:
    enabled: true
    dir: /loki/wal
  chunk_idle_period: 5m
  max_chunk_age: 2h
  lifecycler:
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1

schema_config:
  configs:
    - from: 2020-10-24
      store: boltdb-shipper
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h

storage_config:
  boltdb_shipper:
    active_index_directory: /loki/index
    cache_location: /loki/boltdb-cache
    shared_store: filesystem
  filesystem:
    directory: /loki/chunks

chunk_store_config:
  max_look_back_period: 336h   # 14 days

table_manager:
  retention_deletes_enabled: true
  retention_period: 336h       # 14 days

compactor:
  working_directory: /loki/compactor
  shared_store: filesystem
  compaction_interval: 5m

# Query path tuning (helps with "too many outstanding requests")
frontend:
  max_outstanding_per_tenant: 2048
frontend_worker:
  parallelism: 4
querier:
  max_concurrent: 16

query_scheduler:
  max_outstanding_requests_per_tenant: 2048

limits_config:
  ingestion_rate_mb: 8
  ingestion_burst_size_mb: 16
  max_query_length: 168h
  max_query_parallelism: 16
  max_entries_limit_per_query: 5000
  max_query_series: 1000        # <-- was max_series_per_query (invalid)
  reject_old_samples: true
  reject_old_samples_max_age: 168h
  retention_period: 336h